# 숫자 자료형 
print(5)
print(-10)
print(3.14)
print(1000)
print(5+3)
print(2*8)
print(3*(3+1))
# 문자 자료형
print('풍선')
print("나비")
print("ㅋ"*9)
# boolean(불리안)자료형 참/거짓
print('boolean(불리안)자료형 참/거짓')
print(5>10)
print(5<10)
print(True)
print(False)
print(not True)
print(not False)
print(not (5>10))
print(not (5<10))
